
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Audit, User, Incident } from '../types';
import { InspectionResult } from '../types';

export const generateAuditPDF = (audit: Audit, currentUser: User) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // --- Brand Colors ---
  const brandBlue = '#2563eb';
  const brandGray = '#6b7280';
  const passColor = '#16a34a';
  const failColor = '#dc2626';

  // --- Header Section ---
  doc.setFontSize(22);
  doc.setTextColor(brandBlue);
  doc.setFont('helvetica', 'bold');
  doc.text("Hotel Audit Pro", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(brandGray);
  doc.setFont('helvetica', 'normal');
  doc.text("Quality & Hygiene Report", 14, 26);
  
  // Draw divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 30, pageWidth - 14, 30);

  // --- Audit Details Section ---
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(audit.title, 14, 42);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);

  const leftColX = 14;
  const rightColX = pageWidth / 2 + 10;
  let currentY = 52;
  const lineHeight = 6;

  // Metadata Grid
  doc.setFont('helvetica', 'bold');
  doc.text("Department:", leftColX, currentY);
  doc.setFont('helvetica', 'normal');
  doc.text(audit.department, leftColX + 25, currentY);

  doc.setFont('helvetica', 'bold');
  doc.text("Status:", rightColX, currentY);
  doc.setFont('helvetica', 'normal');
  doc.text(audit.status, rightColX + 25, currentY);

  currentY += lineHeight;

  doc.setFont('helvetica', 'bold');
  doc.text("Due Date:", leftColX, currentY);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(audit.dueDate).toLocaleDateString(), leftColX + 25, currentY);

  doc.setFont('helvetica', 'bold');
  doc.text("Completed:", rightColX, currentY);
  doc.setFont('helvetica', 'normal');
  doc.text(audit.completedDate || 'In Progress', rightColX + 25, currentY);

  currentY += lineHeight;
  
  doc.setFont('helvetica', 'bold');
  doc.text("Generated By:", leftColX, currentY);
  doc.setFont('helvetica', 'normal');
  doc.text(currentUser.name, leftColX + 25, currentY);

  // --- Stats Calculation ---
  const totalItems = audit.items.length;
  const passedCount = audit.items.filter(i => i.result === InspectionResult.Pass).length;
  const failedCount = audit.items.filter(i => i.result === InspectionResult.Fail).length;
  const naCount = audit.items.filter(i => i.result === InspectionResult.NA).length;
  const pendingCount = totalItems - passedCount - failedCount - naCount;
  
  // Calculate Score
  const score = totalItems > 0 
    ? Math.round((passedCount / totalItems) * 100) 
    : 0;

  // --- Summary Breakdown ---
  currentY += lineHeight * 2;
  doc.setDrawColor(230, 230, 230);
  doc.line(14, currentY - 4, pageWidth - 14, currentY - 4);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("Executive Summary", 14, currentY + 1);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  
  // Draw summary badges/text
  let badgeX = 14;
  const badgeY = currentY + 8;
  
  // Pass Count
  doc.setTextColor(passColor);
  doc.text(`PASS: ${passedCount}`, badgeX, badgeY);
  badgeX += 25;

  // Fail Count
  doc.setTextColor(failColor);
  doc.text(`FAIL: ${failedCount}`, badgeX, badgeY);
  badgeX += 25;
  
  // Other Counts
  doc.setTextColor(100, 100, 100);
  doc.text(`N/A: ${naCount}`, badgeX, badgeY);
  badgeX += 20;
  doc.text(`Pending: ${pendingCount}`, badgeX, badgeY);

  // --- Score Box (Top Right) ---
  const scoreBoxY = 40;
  const scoreBoxWidth = 30;
  const scoreBoxX = pageWidth - 14 - scoreBoxWidth;
  
  doc.setDrawColor(brandBlue);
  doc.setLineWidth(0.5);
  doc.roundedRect(scoreBoxX, scoreBoxY, scoreBoxWidth, 20, 2, 2, 'S');

  doc.setFontSize(8);
  doc.setTextColor(brandBlue);
  doc.text("SCORE", scoreBoxX + scoreBoxWidth/2, scoreBoxY + 6, { align: 'center' });

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(score >= 80 ? passColor : score >= 50 ? '#d97706' : failColor); // Green, Orange, or Red
  doc.text(`${score}%`, scoreBoxX + scoreBoxWidth/2, scoreBoxY + 16, { align: 'center' });


  // --- Inspection Items Table ---
  const tableBody = audit.items.map((item, index) => {
    let resultText = item.result || 'Pending';
    
    const description = `${index + 1}. ${item.description}`;
    const assignee = item.assignee || 'Unassigned';
    
    const notes = item.notes ? `Note: ${item.notes}` : '';
    const temp = item.temperature ? `Temp: ${item.temperature}°F` : '';
    const hasPhoto = item.photo ? '[Photo Evidence Attached]' : '';
    
    // Combine details into a clean multiline string
    const details = [temp, notes, hasPhoto].filter(Boolean).join('\n');

    return [
      description,
      assignee,
      resultText,
      details
    ];
  });

  autoTable(doc, {
    startY: currentY + 15,
    head: [['Inspection Item', 'Assignee', 'Result', 'Details / Observations']],
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: '#2563eb',
      textColor: '#ffffff',
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      valign: 'top', // Top align for better readability with multiline details
      overflow: 'linebreak',
    },
    columnStyles: {
      0: { cellWidth: 'auto' }, 
      1: { cellWidth: 35, fontSize: 8, textColor: '#4b5563' }, // Assignee Column
      2: { cellWidth: 25, halign: 'center', fontStyle: 'bold' }, // Result Column
      3: { cellWidth: 50, fontSize: 8, textColor: '#4b5563' }  // Details Column
    },
    didParseCell: function(data) {
        // Color coding for results
        if (data.section === 'body' && data.column.index === 2) {
            if (data.cell.raw === 'Pass') {
                data.cell.styles.textColor = passColor;
            } else if (data.cell.raw === 'Fail') {
                data.cell.styles.textColor = failColor;
            } else {
                data.cell.styles.textColor = '#9ca3af'; // Gray for Pending/NA
            }
        }
    }
  });

  // --- Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    const footerText = `Generated on ${new Date().toLocaleString()} by Hotel Audit Pro`;
    doc.text(footerText, 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 25, doc.internal.pageSize.height - 10);
  }

  const safeTitle = audit.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`${safeTitle}_report.pdf`);
};

export const generateIncidentPDF = (incident: Incident, currentUser: User) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    const brandRed = '#dc2626';
    const brandBlue = '#2563eb';
    const brandGray = '#6b7280';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(incident.priority === 'Critical' ? brandRed : brandBlue);
    doc.setFont('helvetica', 'bold');
    doc.text("Incident Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(brandGray);
    doc.setFont('helvetica', 'normal');
    doc.text(`ID: ${incident.id}`, 14, 26);
    doc.line(14, 30, pageWidth - 14, 30);

    // Main Details
    let y = 42;
    doc.setTextColor(0,0,0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(incident.title, 14, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const addField = (label: string, value: string) => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${label}:`, 14, y);
        doc.setFont('helvetica', 'normal');
        doc.text(value, 40, y);
        y += 7;
    };

    addField("Type", incident.type || 'Unspecified');
    addField("Priority", incident.priority);
    addField("Status", incident.status);
    addField("Dept", incident.department);
    addField("Assignee", incident.assignee || 'Unassigned');
    addField("Reported", new Date(incident.reportedAt).toLocaleString());

    // Description
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.text("Description:", 14, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(incident.description, pageWidth - 28);
    doc.text(descLines, 14, y);
    y += descLines.length * 5 + 5;

    // History Log Table
    doc.setFont('helvetica', 'bold');
    doc.text("Activity History (Audit Trail):", 14, y);
    y += 5;

    if (incident.history && incident.history.length > 0) {
        autoTable(doc, {
            startY: y,
            head: [['Time', 'Action', 'User', 'Details']],
            body: incident.history.map(h => [
                new Date(h.timestamp).toLocaleString(),
                h.action,
                h.user,
                h.details || ''
            ]),
            theme: 'striped',
            headStyles: { fillColor: incident.priority === 'Critical' ? brandRed : brandBlue },
            styles: { fontSize: 8 }
        });
    } else {
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100);
        doc.text("No history log recorded.", 14, y + 5);
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        const footerText = `Generated on ${new Date().toLocaleString()} by Hotel Audit Pro - User: ${currentUser.name}`;
        doc.text(footerText, 14, doc.internal.pageSize.height - 10);
    }

    doc.save(`incident_${incident.id}.pdf`);
};
